imgs:
  img0:
    type: nature
    src: http://wangzc.cc/gallery/nature/images/thumbs/01.jpg
  img1:
    type: nature
    src: http://wangzc.cc/gallery/nature/images/thumbs/02.jpg
  img2:
    type: nature
    src: http://wangzc.cc/gallery/nature/images/thumbs/03.jpg
  img3:
    type: nature
    src: http://wangzc.cc/gallery/nature/images/thumbs/04.jpg
  img4:
    type: travel
    src: http://wangzc.cc/gallery/travel/images/thumbs/05.jpg
  img5:
    type: travel
    src: http://wangzc.cc/gallery/travel/images/thumbs/06.jpg
  img6:
    type: travel
    src: http://wangzc.cc/gallery/travel/images/thumbs/07.jpg
  img7:
    type: shenzhen
    src: http://wangzc.cc/gallery/shenzhen/images/thumbs/01.jpg
  img8:
    type: shenzhen
    src: http://wangzc.cc/gallery/shenzhen/images/thumbs/02.jpg
  img9:
    type: shenzhen
    src: http://wangzc.cc/gallery/shenzhen/images/thumbs/03.jpg
  img10:
    type: friends
    src: http://wangzc.cc/gallery/friends/images/thumbs/01.jpg
  img11:
    type: friends
    src: http://wangzc.cc/gallery/friends/images/thumbs/02.jpg